# Generated by Django 5.0.4 on 2024-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('shipment', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('packing_carton', models.CharField(max_length=200)),
                ('pieces_packing', models.CharField(max_length=200)),
                ('remaining_orders', models.CharField(max_length=200)),
                ('stock_srt', models.CharField(max_length=200)),
                ('stock_jwd', models.CharField(max_length=200)),
                ('srt11', models.CharField(max_length=200)),
                ('srt12', models.CharField(max_length=200)),
                ('srt13', models.CharField(max_length=200)),
                ('srt14', models.CharField(max_length=200)),
                ('srt2', models.CharField(max_length=200)),
                ('srt3', models.CharField(max_length=200)),
                ('total_stock', models.CharField(max_length=200)),
                ('balance_stock', models.CharField(max_length=200)),
                ('rm_pending', models.CharField(max_length=200)),
            ],
        ),
    ]
