# Generated by Django 5.0.4 on 2024-04-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
